### ISSUE TITLE
Values in registry that should be numbers/integers are indexed as strings in JSON API response

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/harvest#153] opened 2023-12-06 02:42 UTC
### 💡 Description

- Check if the gt, lt... operators still work on numbers in q parameter.
- Trace back when/how/why the change was introduced
- Decide if we want to come back to the previous behavior

**Comment by tloubrieu-jpl** [comment] 2024-02-02 23:15
@alexdunnjpl @jordanpadams I moved the ticket to the harvest repository, from what was said before I suggest 2 actions:

1. check that the latest version harvest is not breaking the schema
2. develop a utility to make the schema straight, could include a feature for the ticket https://github.com/NASA-PDS/registry-api/issues/351. Ths development could be a sub-script of registry-manager or registry-sweeper, my first thought was to make it part of registry-manager/registry-common.

**Comment by tloubrieu-jpl** [comment] 2024-02-06 21:43
The properties which we expect to be number are:

```
      "pds:Record_Character.pds:record_length" : [ "110" ],
      "pds:File.pds:file_size" : [ "3850" ],
      "pds:Table_Character.pds:records" : [ "35" ],
```

As seen in request https://pds.nasa.gov/api/search/1/products

**Comment by jordanpadams** [comment] 2024-02-15 21:55
@alexdunnjpl I have no idea what is going on here... Will try out all the registries. not sure how this is possible

**Comment by jordanpadams** [comment] 2024-02-15 22:01
It looks like the collection is there, but the product is not...

**Comment by jordanpadams** [comment] 2024-02-15 22:07
@alexdunnjpl actually I lied.
```
curl -u <user> 'https://search-sbnumd-prod-o5i2rnn265gnwmv2quk4n7uram.us-west-2.es.amazonaws.com/registry/_search?q={_id:"urn:nasa:pds:compil-comet:nuc_properties:extinct::1.0"}&pretty=true'
```

**Comment by alexdunnjpl** [comment] 2024-02-15 23:19
Sorry @jordanpadams - didn't mean to send you off to do the thing I was lazily avoiding!

So the issue with the "missing" property mappings was that I forgot to convert them `.`->`/` :man_facepalming: 

The good-ish news is that those are all mapped as `long` in the index, so there's no issue with harvest.  Flicking this back to registry-api.

**Comment by alexdunnjpl** [comment] 2024-02-15 23:41
More good-ish news.

Searches appear to respect the mapping type, i.e. when performing comparisons the values aren't compared lexicographically and therefore aren't returning erroneous results.

ex. this query

```JSON
{
    "query": {
        "bool": {
            "must": [
                {
                    "range": {
                        "pds:File/pds:records": {
                            "gte": 0,
                            "lte": 35
                        }
                    }
                }
            ]
        }
    },
    "_source": {
        "includes": ["pds:File/pds:records"]
    },
    "size": 3,
    "track_total_hits": true
}
```
returns the following (note presence of value `"7"`)

```JSON
{
    "took": 4,
    "timed_out": false,
    "_shards": {
        "total": 3,
        "successful": 3,
        "skipped": 0,
        "failed": 0
    },
    "hits": {
        "total": {
            "value": 150,
            "relation": "eq"
        },
        "max_score": 1.0,
        "hits": [
            {
                "_index": "registry",
                "_type": "_doc",
                "_id": "urn:nasa:pds:compil-comet:nuc_properties:extinct::1.0",
                "_score": 1.0,
                "_source": {
                    "pds:File/pds:records": [
                        "35"
                    ]
                }
            },
            {
                "_index": "registry",
                "_type": "_doc",
                "_id": "urn:nasa:pds:gbo-kpno:mosaic-9p:reduced_2005_july0_conv_stand_july04_tab::1.0",
                "_score": 1.0,
                "_source": {
                    "pds:File/pds:records": [
                        "7"
                    ]
                }
            },
            {
                "_index": "registry",
                "_type": "_doc",
                "_id": "urn:nasa:pds:gbo-kpno:mosaic-9p:reduced_200_standards_centers_july04_tab::1.0",
                "_score": 1.0,
                "_source": {
                    "pds:File/pds:records": [
                        "31"
                    ]
                }
            }
        ]
    }
}
```

**Comment by alexdunnjpl** [comment] 2024-02-16 00:00
Testing via the API appears to indicate that comparisons are being correctly performed:

```
~$ curl -s --get 'https://pds.nasa.gov/api/search-en/1/products'   --data-urlencode 'limit=0'   --data-urlencode 'q=(pds:File.pds:records gt "100")'   --data-urlencode 'start=0'   -H 'accept: application/json' | jq .summary.hits
1194175
~$ curl -s --get 'https://pds.nasa.gov/api/search-en/1/products'   --data-urlencode 'limit=0'   --data-urlencode 'q=(pds:File.pds:records gt "1000")'   --data-urlencode 'start=0'   -H 'accept: application/json' | jq .summary.hits
501838
~$ curl -s --get 'https://pds.nasa.gov/api/search-en/1/products'   --data-urlencode 'limit=0'   --data-urlencode 'q=(pds:File.pds:records gt "10000")'   --data-urlencode 'start=0'   -H 'accept: application/json' | jq .summary.hits
150101
parallels@parallels-Parallels-Virtual-Platform:~$ curl -s --get 'https://pds.nasa.gov/api/search-en/1/products'   --data-urlencode 'limit=0'   --data-urlencode 'q=(pds:File.pds:records gt "100000")'   --data-urlencode 'start=0'   -H 'accept: application/json' | jq .summary.hits
19194
~$ curl -s --get 'https://pds.nasa.gov/api/search-en/1/products'   --data-urlencode 'limit=0'   --data-urlencode 'q=(pds:File.pds:records gt "1000000")'   --data-urlencode 'start=0'   -H 'accept: application/json' | jq .summary.hits
219
~$ curl -s --get 'https://pds.nasa.gov/api/search-en/1/products'   --data-urlencode 'limit=0'   --data-urlencode 'q=(pds:File.pds:records gt "10000000")'   --data-urlencode 'start=0'   -H 'accept: application/json' | jq .summary.hits
11

```

Note that records `gt` threshold is increasing tenfold each time, and hits count is being reduced drastically in a manner inconsistent with lexicographic comparison, which should result in fairly consistent hit counts.

@tloubrieu-jpl @jordanpadams with this in mind, what disconnect, if any, still exists between current and desired behaviour, and is it a regression, or a new feature (if that's known for certain)?

**Comment by alexdunnjpl** [comment] 2024-02-16 16:50
Roger that - thanks Jordan!

**Comment by jordanpadams** [comment] 2024-02-20 21:15
@alexdunnjpl per my comment on our Sprint Tag, it doesn't look like there is a way for me to look this up. I just see this screenshot that there is something out there.

<img width="1086" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNlIxQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--803df13303409e5eada5b87ab02fb1511abe823e/Screenshot%202024-02-20%20at%208.16.56%E2%80%AFAM.png" alt="Screenshot 2024-02-20 at 8.16.56 AM.png" />

Is there any way we can just develop a generic sweeper that goes through fields and checks their type matches what we have in the schema types?

**Comment by alexdunnjpl** [comment] 2024-02-20 21:43
@jordanpadams sure can!  You just want detection/report, or with automatic sync and re-index?

What should the source of truth be for mapping fields onto their correct opensearch index mapping type?

**Comment by jordanpadams** [comment] 2024-02-20 22:12
@alexdunnjpl the source of truth is the JSON files online ([e.g. this one](https://pds.nasa.gov/pds4/pds/v1/PDS4_PDS_1L00.JSON)). see Harvest for how it gets those files.

**Comment by jordanpadams** [comment] 2024-03-19 17:18
@alexdunnjpl @tloubrieu-jpl have we figured out what is going on here? are we good to close this out or is there still work to be done?

**Comment by alexdunnjpl** [comment] 2024-03-19 18:54
@jordanpadams implementation of your two items in the previous comment are still outstanding.

We can close this ticket iff tickets exist for those two items, otherwise this should stay open.  Probably best to split into new tickets since 1 will take much less time than 2.

**Comment by jordanpadams** [comment] 2024-03-26 22:32
@alexdunnjpl correct. I don't think this is really a registry-mgr or harvest thing to date. They both work with LDDs and trying to strongly type things in the schema, but nothing specifically dealing with manipulating or reviewing the schema after the fact

**Comment by jordanpadams** [comment] 2024-08-03 00:20
created NASA-PDS/registry-sweepers#128 and NASA-PDS/registry-sweepers#129. closing this one.

**Closed by jordanpadams** 2024-08-03 00:20 UTC
Labels: bug, B14.1, B15.0, p.must-have, sprint-backlog, s.medium
