### ISSUE TITLE
Change the initialization value for archive_status

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/harvest#115] opened 2022-12-09 01:26 UTC
## 💡 Description

According to comment in https://github.com/NASA-PDS/pds-api/issues/221#issuecomment-1343581767

**Comment by jordanpadams** [comment] 2023-10-03 12:09
closing as duplicate of #115 and the other one contains more info for a requirement

**Closed by jordanpadams** 2023-10-03 12:09 UTC
Labels: B13.1, icebox, task, i&t.skip
