### ISSUE TITLE
`Data too large` error from very large data products

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/harvest#133] opened 2023-09-27 22:12 UTC
### Checked for duplicates

Yes - I've already checked

### 🐛 Describe the bug

When I did a harvest of a data set with some very large data products, I get a `data too large` error and the data is not loaded into the Registry.

### 🕵️ Expected behavior

I expected the loaded would be nominally loaded into the Registry.

### 📜 To Reproduce

1. Download TBD data product
2. Attempt to harvest the product
3. Note the error

```
[ERROR] LIDVID = urn:esa:psa:em16_tgo_acs:data_raw:acs_raw_hk_nir_20170907t000000-20170907t055959::3.0, 
Message = [parent] Data too large, data for [indices:data/write/bulk[s]] would be [16591820628/15.4gb], 
which exceeds the limit of [16287753830/15.1gb]. Current usage: [16591415264/15.4gb], new bytes reserved: [405364/395.8kb], 
usages [request=0/0b, fielddata=0/0b, in_flight_requests=405364/395.8kb, accounting=613644/599.2kb]
```

### 🖥 Environment Info

Linux

### 📚 Version of Software Used

3.7.6

### 🩺 Test Data / Additional context

TBD

**Comment by alexdunnjpl** [comment] 2023-09-27 23:36
@jordanpadams what's the best way to get a copy of the label for this product?

**Comment by jordanpadams** [comment] 2023-09-28 15:19
@alexdunnjpl a ping is out to the user.

**Comment by alexdunnjpl** [comment] 2023-10-03 23:35
@jordanpadams looking deeper into this error, it [appears to be due to imminent exhaustion of the JVM heap on OpenSearch, rather than any one request/product being too large.](https://discuss.elastic.co/t/what-does-this-error-mean-data-too-large-data-for-transport-request/209345/3)  (Presumably RAM allocation is currently 16GB on that node)

The fix here is to bump up the instance size to cope with peak throughput, and/or incorporate pause/retry behaviour in harvest.

Closing as a duplicate of #125 on that basis, since the fix for that is a fix for this.

**Closed by alexdunnjpl** 2023-10-03 23:35 UTC
Labels: bug, B14.1, s.medium

**Comment by jordanpadams** [comment] 2023-10-04 16:43
@alexdunnjpl nice sleuthing. 🎉

**Comment by sjoshi-jpl** [comment] 2023-10-04 17:42
@alexdunnjpl yes this was recently bumped up based on our last conversation with @jordanpadams and @tloubrieu-jpl as we discussed how PSA could be as large / resource intensive as GEO.
